server:
  port: 8092
spring:
  application:
    name: simple-weatherinfo
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
management:
  endpoint:
    web:
      exposure:
        include: "logfile"